// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PzKx_0Bo7lT-5Ni_ufsOESqfG-BYxcs',
    appId: '1:1048559008207:web:76995dc71a8d6ea364faba',
    messagingSenderId: '1048559008207',
    projectId: 'social-app-25853',
    authDomain: 'social-app-25853.firebaseapp.com',
    storageBucket: 'social-app-25853.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1PzKx_0Bo7lT-5Ni_ufsOESqfG-BYxcs',
    appId: '1:1048559008207:android:76995dc71a8d6ea364faba',
    messagingSenderId: '1048559008207',
    projectId: 'social-app-25853',
    storageBucket: 'social-app-25853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUG31XFBiUovF9SP5Ic4mmSfWuQXQS794',
    appId: '1:1048559008207:ios:fea53fc11c90b09064faba',
    messagingSenderId: '1048559008207',
    projectId: 'social-app-25853',
    storageBucket: 'social-app-25853.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUG31XFBiUovF9SP5Ic4mmSfWuQXQS794',
    appId: '1:1048559008207:ios:fea53fc11c90b09064faba',
    messagingSenderId: '1048559008207',
    projectId: 'social-app-25853',
    storageBucket: 'social-app-25853.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1PzKx_0Bo7lT-5Ni_ufsOESqfG-BYxcs',
    appId: '1:1048559008207:web:76995dc71a8d6ea364faba',
    messagingSenderId: '1048559008207',
    projectId: 'social-app-25853',
    authDomain: 'social-app-25853.firebaseapp.com',
    storageBucket: 'social-app-25853.firebasestorage.app',
  );
}
